// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/wheel": {
    params: {};
  };
  "/dice": {
    params: {};
  };
  "/coin": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/wheel" | "/dice" | "/coin";
  };
  "./routes/layout.tsx": {
    id: "routes/layout";
    page: "/" | "/wheel" | "/dice" | "/coin";
  };
  "./routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "./routes/wheel.tsx": {
    id: "routes/wheel";
    page: "/wheel";
  };
  "./routes/dice.tsx": {
    id: "routes/dice";
    page: "/dice";
  };
  "./routes/coin.tsx": {
    id: "routes/coin";
    page: "/coin";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "routes/layout": typeof import("./src/./routes/layout.tsx");
  "routes/home": typeof import("./src/./routes/home.tsx");
  "routes/wheel": typeof import("./src/./routes/wheel.tsx");
  "routes/dice": typeof import("./src/./routes/dice.tsx");
  "routes/coin": typeof import("./src/./routes/coin.tsx");
};